server.port = 7000

spring.datasource.url = jdbc:postgresql://localhost:5432/Timely
spring.datasource.username = postgres
spring.datasource.password = passvord123

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none


spring.jpa.show-sql=false
spring.thymeleaf.cache=false


